# Generated by Django 4.2.2 on 2023-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_retailer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
