# Generated by Django 4.2.2 on 2023-09-14 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_cart',
            field=models.ManyToManyField(blank=True, related_name='cart_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
