# Generated by Django 4.2.2 on 2023-06-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcatogory',
            old_name='catogory',
            new_name='category',
        ),
    ]
