# Generated by Django 4.2.2 on 2023-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_product_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
